### ISSUE TITLE
take out datasquad website info and add to DSC doc

### ISSUE THREAD

**Issue by jt14den** [ucla-imls-open-sci/UCLA-imls-docs#15]
move that as a section to https://github.com/UCLA-DataSquad/ucla-datasquad.github.io. Also, rename that repo to docs

**Comment by lawtlee** [comment]
Did you want me to rename this [repository](https://github.com/ucla-data-science-center/ucla-dsc-docs)? Also do you want me to move it to https://github.com/ucla-data-science-center/ucla-dsc-docs or https://github.com/UCLA-DataSquad/ucla-datasquad.github.io?

**Comment by jt14den** [comment]
yes, docs is simple to me, you can describe it with a fuller name

**Comment by lawtlee** [comment]
did you want me to move that documentation to the dsc docs or the datasquad website?
