### ISSUE TITLE
the site is broken 

### ISSUE THREAD

**Issue by jt14den** [ucla-imls-open-sci/UCLA-imls-docs#23]
@lawtlee can you debug?

**Comment by lawtlee** [comment]
The wrong link was used to link to the site, this is the correct link: https://ucla-imls-open-sci.info/ucla-imls-docs/
I'm not sure why the styling is off though.

**Comment by lawtlee** [comment]
The repository's name change wasn't reflected in the _config.yaml or the updated link.
